models:
    #global model params
    min-workers: 1
    max-workers: 1
    batch-size: 1
    max-batch-delay : 5000
    retry-attempts : 3
    timeout-ms : 20000
    blenderbot-90M:
       url : model-store/blenderbot-90M.mar #local or public URI
      #  min-workers: 1   #override the global params
      #  max-workers: 1
      #  batch-size: 1
    Helsinki-NLP:
       url : model-store/Helsinki-NLP.mar
      #  min-workers: 1
      #  max-workers: 1
      #  batch-size: 1
    gsarti:
       url: model-store/gsarti.mar
      #  min-workers: 1
      #  max-workers: 1
      #  batch-size: 1

 
dag:
#  Helsinki-NLP: [gsarti]
  Helsinki-NLP: [blenderbot-90M]
  blenderbot-90M : [gsarti]
